### ISSUE TITLE
HTTP Status 500 Internal Server Error

### ISSUE THREAD

**Issue by anuragdev2601** [Alperencode/Event-Registration-System#1]
![IMG_20240919_223742.jpg](https://github.com/user-attachments/assets/4ebe82bd-f0cf-4ae7-a3d7-e1d465d295eb)

I think I not create SQL table and I don't know what I fill in in table details

**Comment by Alperencode** [comment]
I'll document that when I have a free time. Are you in a hurry or is it just a hobby thing?

**Comment by anuragdev2601** [comment]
> I'll document that when I have a free time. Are you in a hurry or is it just a hobby thing?

it's argent bcoz currently i want to see as my documentation module

**Comment by anuragdev2601** [comment]
> I'll document that when I have a free time. Are you in a hurry or is it just a hobby thing?

i want to know, how many actors will present in this.
like admin,customer,organizer

**Comment by Alperencode** [comment]
> it's argent bcoz currently i want to see as my documentation module

I didn't quite understand what you mean. Can you write with more clear english please?

**Comment by Alperencode** [comment]
> i want to know, how many actors will present in this. like admin,customer,organizer

There's no admin role in this project. Only two actors presents: organizer and participants. Any participant can create and host their own events and become an organizer.

**Comment by anuragdev2601** [comment]
Actually I am making this for a college project so I need documentation part also and I can make it only by looking at the website.

**Comment by anuragdev2601** [comment]
> > i want to know, how many actors will present in this. like admin,customer,organizer
> 
> There's no admin role in this project. Only two actors presents: organizer and participants. Any participant can create and host their own events and become an organizer.

okay btw whats your reason for creating this website

**Comment by anuragdev2601** [comment]
> > i want to know, how many actors will present in this. like admin,customer,organizer
> 
> There's no admin role in this project. Only two actors presents: organizer and participants. Any participant can create and host their own events and become an organizer.

so who will manage this website

**Comment by Alperencode** [comment]
I just checked it and there is the SQL tables in this repository. You can check them out [here](https://github.com/Alperencode/Event-Registration-System/tree/master/tables). You can import them in MySQL data base using MySQL interface. So there is no need for detailed documentation. Anyone with basic knowledge can setup and use that tables.

The reason for this project was a collage project like yours. And no one will manage this website since its not hosting anywhere. It was meant to be run on local. But anyone can host it with basic operations by paying attention to [MIT License](https://github.com/Alperencode/Event-Registration-System/blob/master/LICENSE). So you can free to use it, but you need to have a basic understanding of web programming.

**Comment by anuragdev2601** [comment]
okay thanks buddy you are awesome.

btw you have any abstrac or module of this project

**Comment by Alperencode** [comment]
No I don't, all source code of the project is available in the repository.

**Comment by anuragdev2601** [comment]
Okay bruh

**Comment by anuragdev2601** [comment]
Hyy bro I connect table SQL with project still error not solve
